require: 
  - rubocop-rails
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Exclude:
    - config/**/*
    - db/**/*

Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: false
  Max: 120

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/PerceivedComplexity:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: key

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
  IndentationWidth: 2

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"