AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - config/**/*
    - db/**/*

Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: false
  Max: 120

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/PerceivedComplexity:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AlignHash:
  EnforcedColonStyle: key

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
  IndentationWidth: 2
