version: "3.9"

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
    args:
      RUBY_VERSION: 2.5.5
      BUNDLER_VERSION: 2.0.2
      NODE_MAJOR: 8
      YARN_VERSION: 1.3.2
      RAILS_ROOT: /app
  networks:
    - svt
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  volumes:
    - .:/app:cached
    - bundle:/usr/local/bundle
    - rails_cache:/app/tmp/cache
    - node_modules:/app/node_modules
    - packs:/app/public/packs
  environment:
    BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
  stdin_open: true
  tty: true
  depends_on:
    - mysql
    - redis

services:
  runner:
    <<: *backend
    command: /bin/bash

  rails:
    <<: *backend
    restart: unless-stopped
    ports:
      - "3000"
    command: bundle exec rails server -b 0.0.0.0

  nginx:
    image: nginx:1.19.6-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - type: bind
        source: ./
        target: /app
      - .docker/nginx/:/etc/nginx/conf.d/
      - .docker/tls/:/etc/pki/tls/nginx/
    stdin_open: true
    tty: true
    networks:
      - svt

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/:/etc/mysql/conf.d/
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root_pwd"
      MYSQL_DATABASE: ${MYSQL_DEV_DATABASE}
      MYSQL_USER: ${MYSQL_DEV_USER}
      MYSQL_PASSWORD: ${MYSQL_DEV_PASSWORD}
    restart: always
    networks:
      - svt

  mysql-test:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/:/etc/mysql/conf.d/
      - mysql-test:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root-test_pwd"
      MYSQL_DATABASE: ${MYSQL_TEST_DATABASE}
      MYSQL_USER: ${MYSQL_TEST_USER}
      MYSQL_PASSWORD: ${MYSQL_TEST_PASSWORD}
    restart: always
    networks:
      - svt

  redis:
    image: redis:5.0
    volumes:
      - redis:/data
    restart: always
    networks:
      - svt

  sidekiq:
    <<: *backend
    restart: unless-stopped
    command: bundle exec sidekiq -C config/sidekiq.yml

  webpacker:
    <<: *app
    ports:
      - "3035:3035"
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    command: ./bin/webpack-dev-server

  guard:
    <<: *backend
    depends_on:
      - mysql-test
    command: bundle exec guard

volumes:
  bundle:
  rails_cache:
  node_modules:
  packs:
  mysql:
  mysql-test:
  redis:

networks:
  svt:
