default: &default
  adapter: redis
  url: <%= "#{ENV['REDIS_URL']}1/cable" %>

development:
  <<: *default
  timeout: 1

test:
  adapter: async

staging:
  <<: *default
  timeout: 1

production:
  <<: *default