development:
#  adapter: async
  adapter: redis
  url: redis://localhost:6379/1/cable

test:
  adapter: async

staging:
  adapter: redis
  url: redis://localhost:6379/1/cable

production:
  adapter: redis
  url: redis://localhost:6379/1/cable