development:
#  adapter: async
  adapter: redis
  url: redis://localhost:6379/1/cable
  timeout: 1

test:
  adapter: async

staging:
  adapter: redis
  url: redis://localhost:6379/1/cable
  timeout: 1

production:
  adapter: redis
  url: redis://localhost:6379/1/cable